package ro.sda.javaro35.finalProject.entities.job;

public enum Categories {

    AGRICULTURE, AUTO, HORECA, BABYSITTER, CLEANING, CHEMISTRY, CONSTRUCTIONS, ENTERTAINMENT,
    EDUCATION, ARTS, ENGINEERING, JOURNALISM, MARKETING, PR, HR, BEAUTY, SPORT, STATISTICS,
    SALES

}
